version: '3.8'

services:
  database: 
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge